// <auto-generated />
using System;
using ManagePassword.Model.DBSide;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ManagePassword.Migrations.ApplicationContextSQLiteMigrations
{
    [DbContext(typeof(ApplicationContextSQLite))]
    [Migration("20250508103728_CreatePasswordCiphersTable")]
    partial class CreatePasswordCiphersTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("ManagePassword.Model.PasswordCipher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Aes_iv")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Password_hash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Salt")
                        .HasColumnType("BLOB");

                    b.Property<string>("Service")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("passwordCiphers");
                });
#pragma warning restore 612, 618
        }
    }
}
